services:
  postgres:
    image: postgres:16-alpine
    container_name: energy_postgres
    environment:
      POSTGRES_USER: energy
      POSTGRES_PASSWORD: energy
      POSTGRES_DB: energy
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
